import { StyleSheet } from "@react-pdf/renderer";

export const pdfColors = {
  ink: "#141413",
  body: "#3d3d3a",
  muted: "#6c6a64",
  hairline: "#e6dfd8",
  sidebarBg: "#f5f0e8",
  compactSidebarBg: "#E8EEF2",
  compactAccent: "#1F4E5F",
  compactOnAccent: "#FFFFFF",
  onInk: "#ffffff",
  ofspaceGold: "#F9CB81",
  ofspaceInk: "#2A2C2E",
  ofspaceMuted: "#6A6B6D",
  ofspaceHighlight: "#E7D4B7",
  ofspaceBarTrack: "#ECECEC",
  ofspacePageBg: "#FFFFFF",
  webDevInk: "#414042",
  webDevBandTop: "#DDDFDE",
  webDevBandBottom: "#FEEDE6",
  webDevPageInner: "#FFFFFF",
};

export const pdfFontFamily = "NotoSans";

export const pdfType = {
  name: 22,
  title: 11,
  section: 9,
  body: 10,
  small: 8.5,
  atsName: 14,
  atsSection: 10,
};

export const pdfSpace = {
  pagePadding: 40,
  sectionGap: 14,
  itemGap: 8,
  bulletIndent: 10,
};

const PDF_PAGE_WIDTH_PT = 595.28;
const PDF_CONTENT_WIDTH_PT = PDF_PAGE_WIDTH_PT - pdfSpace.pagePadding * 2;

export const pdfLayout = {
  sidebarWidthPt: PDF_CONTENT_WIDTH_PT * 0.35,
  bodyWidthPt: PDF_CONTENT_WIDTH_PT * 0.65,
  ofspaceMainWidthPt: PDF_CONTENT_WIDTH_PT * 0.62,
  ofspaceRailWidthPt: PDF_CONTENT_WIDTH_PT * 0.38,
  ofspaceSkillBarWidthPt: 120,
  webDevPageWidthPt: PDF_PAGE_WIDTH_PT,
  /** Card body padding 14×2 + gap 10 — full bleed, không margin hồng. */
  webDevBodyPaddingPt: 14,
  webDevContentWidthPt:
    PDF_PAGE_WIDTH_PT - 14 * 2,
  webDevColumnGapPt: 10,
  webDevLeftWidthPt: (PDF_PAGE_WIDTH_PT - 14 * 2 - 10) * 0.33,
  webDevRightWidthPt: (PDF_PAGE_WIDTH_PT - 14 * 2 - 10) * 0.67,
  webDevInnerMarginPt: 0,
  webDevAvatarSizePt: 99,
};

export const pdfStyles = StyleSheet.create({
  page: {
    padding: pdfSpace.pagePadding,
    fontSize: pdfType.body,
    fontFamily: pdfFontFamily,
    color: pdfColors.body,
    lineHeight: 1.45,
  },
  name: {
    fontSize: pdfType.name,
    color: pdfColors.ink,
    marginBottom: 8,
    fontWeight: 700,
    lineHeight: 1.3,
  },
  title: {
    fontSize: pdfType.title,
    color: pdfColors.muted,
    marginBottom: 6,
    lineHeight: 1.35,
  },
  headerBlock: {
    flexDirection: "column",
    marginBottom: 4,
  },
  contactLine: {
    fontSize: pdfType.small,
    color: pdfColors.muted,
    lineHeight: 1.35,
    marginBottom: 3,
  },
  headerRule: {
    height: 1,
    backgroundColor: pdfColors.hairline,
    marginTop: 6,
    marginBottom: 12,
  },
  contact: {
    fontSize: pdfType.small,
    color: pdfColors.muted,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: pdfType.section,
    color: pdfColors.ink,
    fontWeight: 700,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginTop: pdfSpace.sectionGap,
    marginBottom: 6,
  },
  sectionTitlePlain: {
    fontSize: pdfType.atsSection,
    color: pdfColors.ink,
    fontWeight: 700,
    textTransform: "uppercase",
    marginTop: 10,
    marginBottom: 4,
  },
  rule: {
    height: 1,
    backgroundColor: pdfColors.hairline,
    marginTop: 8,
    marginBottom: 12,
  },
  bullet: {
    marginLeft: pdfSpace.bulletIndent,
    marginBottom: 3,
    fontSize: pdfType.body,
  },
  bodyText: {
    fontSize: pdfType.body,
    color: pdfColors.body,
    marginBottom: 4,
  },
  mutedLine: {
    fontSize: pdfType.small,
    color: pdfColors.muted,
    marginBottom: 4,
  },
  roleLine: {
    fontSize: 11,
    color: pdfColors.ink,
    fontWeight: 700,
    marginBottom: 2,
  },
  row: { flexDirection: "row" },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  sidebar: {
    width: "32%",
    padding: 12,
    backgroundColor: pdfColors.sidebarBg,
    marginRight: 12,
  },
  bodyCol: { width: "68%", flexGrow: 1 },
  sidebarBlock: { marginBottom: 10 },
  contentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  compactSidebar: {
    width: "35%",
    padding: 12,
    paddingTop: 0,
    marginRight: 10,
    flexGrow: 0,
  },
  compactBody: {
    width: "65%",
    flexGrow: 1,
  },
  compactProfileName: {
    fontSize: 20,
    fontWeight: 700,
    color: pdfColors.ink,
    lineHeight: 1.25,
    marginBottom: 4,
    textAlign: "center",
  },
  compactProfileTitle: {
    fontSize: pdfType.title,
    color: pdfColors.muted,
    lineHeight: 1.35,
    marginBottom: 8,
    textAlign: "center",
  },
  compactAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    objectFit: "cover",
    alignSelf: "center",
    marginBottom: 12,
  },
  compactAvatarPlaceholder: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 1,
    borderColor: pdfColors.hairline,
    alignSelf: "center",
    marginBottom: 12,
  },
  compactSectionBar: {
    backgroundColor: pdfColors.compactAccent,
    paddingVertical: 5,
    paddingHorizontal: 8,
    marginBottom: 8,
    marginTop: 4,
  },
  compactSectionBarText: {
    fontSize: 8.5,
    fontWeight: 700,
    color: pdfColors.compactOnAccent,
    textTransform: "uppercase",
  },
  compactSectionBarTextEn: {
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  timelineSectionRow: {
    flexDirection: "row",
    marginBottom: 10,
  },
  timelineTrack: {
    width: 12,
    alignItems: "center",
    marginRight: 8,
    paddingTop: 2,
  },
  timelineDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: pdfColors.ink,
  },
  timelineLine: {
    width: 1,
    flexGrow: 1,
    minHeight: 20,
    backgroundColor: pdfColors.hairline,
    marginTop: 3,
  },
  timelineBody: {
    flexGrow: 1,
    flexShrink: 1,
  },
  timelineHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 3,
  },
  timelineTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.ink,
    flexGrow: 1,
    maxWidth: "72%",
  },
  timelineDate: {
    fontSize: pdfType.small,
    color: pdfColors.muted,
    textAlign: "right",
  },
  roleLineEn: {
    fontSize: 10,
    fontWeight: 700,
    color: pdfColors.ink,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  sidebarSkillBullet: {
    marginLeft: pdfSpace.bulletIndent,
    marginBottom: 2,
    fontSize: 8,
    color: pdfColors.body,
    lineHeight: 1.3,
  },
  compactContactRow: {
    flexDirection: "row",
    marginBottom: 4,
    alignItems: "flex-start",
  },
  compactContactIcon: {
    width: 14,
    fontSize: 8,
    color: pdfColors.muted,
  },
  compactContactLabel: {
    fontSize: 7.5,
    fontWeight: 600,
    color: pdfColors.muted,
    width: 42,
  },
  compactContactValue: {
    fontSize: 8.5,
    color: pdfColors.body,
    flexGrow: 1,
    flexShrink: 1,
  },
  compactSkillGroupLabel: {
    fontSize: 8,
    fontWeight: 700,
    color: pdfColors.ink,
    textTransform: "uppercase",
    marginTop: 4,
    marginBottom: 2,
  },
  compactSkillGroupItems: {
    fontSize: 8,
    color: pdfColors.body,
    lineHeight: 1.35,
    marginBottom: 4,
  },
  compactExperienceCompany: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.ink,
    flexGrow: 1,
    maxWidth: "72%",
  },
  compactExperienceDate: {
    fontSize: pdfType.small,
    color: pdfColors.muted,
    textAlign: "right",
  },
  compactRoleCaps: {
    fontSize: 10,
    fontWeight: 700,
    color: pdfColors.ink,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  compactEntryDivider: {
    height: 1,
    backgroundColor: pdfColors.hairline,
    marginVertical: 6,
  },
  compactEntryBlock: {
    marginBottom: 8,
  },
  ofspaceHeader: {
    flexDirection: "column",
    marginBottom: 12,
  },
  ofspaceName: {
    fontSize: 26,
    fontWeight: 700,
    color: pdfColors.ofspaceGold,
    marginBottom: 6,
    lineHeight: 1.2,
  },
  ofspaceTitle: {
    fontSize: 16,
    fontWeight: 500,
    color: pdfColors.ofspaceMuted,
    marginBottom: 4,
    lineHeight: 1.3,
  },
  ofspaceContentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 18,
  },
  ofspaceMainColumn: {
    width: "58%",
    flexGrow: 0,
    flexShrink: 0,
    paddingRight: 4,
  },
  ofspaceRailColumn: {
    width: "42%",
    flexGrow: 0,
    flexShrink: 0,
    paddingLeft: 2,
  },
  ofspaceSectionBlock: {
    marginBottom: 14,
  },
  ofspaceSectionTitleWrap: {
    marginBottom: 8,
    marginTop: 2,
  },
  ofspaceSectionTitleText: {
    fontSize: 13,
    fontWeight: 700,
    color: pdfColors.ofspaceInk,
    marginBottom: 3,
  },
  ofspaceSectionHighlightBar: {
    height: 6,
    backgroundColor: pdfColors.ofspaceHighlight,
    opacity: 0.25,
    marginBottom: 2,
  },
  ofspaceBodyText: {
    fontSize: 9,
    color: pdfColors.ofspaceInk,
    lineHeight: 1.4,
    opacity: 0.9,
  },
  ofspaceSkillRow: {
    marginBottom: 8,
    width: "100%",
  },
  ofspaceSkillName: {
    fontSize: 10,
    fontWeight: 500,
    color: pdfColors.ofspaceInk,
    marginBottom: 2,
  },
  ofspaceContactRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  ofspaceContactIconCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: pdfColors.ofspaceGold,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    flexShrink: 0,
  },
  ofspaceContactIconLetter: {
    fontSize: 7,
    fontWeight: 700,
    color: pdfColors.ofspaceInk,
    textAlign: "center",
    lineHeight: 1,
  },
  ofspaceContactValue: {
    fontSize: 9,
    color: pdfColors.ofspaceInk,
    opacity: 0.8,
    flexGrow: 1,
    flexShrink: 1,
    lineHeight: 1.35,
    maxWidth: "85%",
  },
  ofspaceExperienceCompany: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.ofspaceInk,
    marginBottom: 2,
  },
  ofspaceExperienceMetaRow: {
    flexDirection: "column",
    marginBottom: 5,
  },
  ofspaceExperienceRole: {
    fontSize: 9,
    color: pdfColors.ofspaceMuted,
    opacity: 0.75,
    marginBottom: 2,
  },
  ofspaceExperienceDate: {
    fontSize: 9,
    color: pdfColors.ofspaceMuted,
    opacity: 0.75,
  },
  ofspaceBullet: {
    fontSize: 9,
    color: pdfColors.ofspaceInk,
    lineHeight: 1.4,
    marginBottom: 3,
    marginLeft: 8,
    opacity: 0.9,
  },
  ofspaceEntryBlock: {
    marginBottom: 8,
  },
  ofspaceProjectBlock: {
    marginBottom: 10,
    marginTop: 4,
  },
  ofspaceProjectName: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.ofspaceInk,
    marginBottom: 2,
  },
  ofspaceProjectTech: {
    fontSize: 9,
    color: pdfColors.ofspaceMuted,
    opacity: 0.75,
    marginBottom: 3,
  },
  ofspaceEntryDivider: {
    height: 1,
    backgroundColor: pdfColors.hairline,
    marginVertical: 6,
  },
  ofspaceEducationWrap: {
    marginBottom: 10,
    paddingBottom: 4,
  },
  ofspaceEducationDegree: {
    fontSize: 11,
    fontWeight: 600,
    color: pdfColors.ofspaceInk,
    marginBottom: 4,
    lineHeight: 1.35,
  },
  ofspaceEducationMeta: {
    fontSize: 9,
    color: pdfColors.ofspaceMuted,
    lineHeight: 1.35,
    marginBottom: 2,
  },
  ofspaceProjectsSection: {
    marginTop: 6,
    marginBottom: 12,
  },
  ofspaceCertTitle: {
    fontSize: 10,
    fontWeight: 600,
    color: pdfColors.ofspaceInk,
    marginBottom: 2,
  },
  ofspaceCertMeta: {
    fontSize: 9,
    color: pdfColors.ofspaceMuted,
    opacity: 0.7,
    marginBottom: 8,
  },
  ofspaceLanguagesText: {
    fontSize: 9,
    color: pdfColors.ofspaceInk,
    opacity: 0.8,
  },
  webDevPage: {
    padding: 0,
    fontFamily: pdfFontFamily,
    fontSize: 9,
    color: pdfColors.webDevInk,
    backgroundColor: pdfColors.webDevPageInner,
  },
  webDevCard: {
    backgroundColor: pdfColors.webDevPageInner,
    width: "100%",
    minHeight: "100%",
  },
  webDevBandTopStrip: {
    height: 28,
    backgroundColor: pdfColors.webDevBandTop,
  },
  webDevCardBody: {
    paddingHorizontal: pdfLayout.webDevBodyPaddingPt,
    paddingTop: 10,
    paddingBottom: 10,
  },
  webDevContentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    width: pdfLayout.webDevContentWidthPt,
    gap: pdfLayout.webDevColumnGapPt,
  },
  webDevLeftColumn: {
    width: pdfLayout.webDevLeftWidthPt,
    flexGrow: 0,
    flexShrink: 0,
  },
  webDevRightColumn: {
    width: pdfLayout.webDevRightWidthPt,
    flexGrow: 0,
    flexShrink: 0,
  },
  webDevName: {
    fontSize: 22,
    fontWeight: 700,
    color: pdfColors.webDevInk,
    marginBottom: 3,
    lineHeight: 1.15,
  },
  webDevTitle: {
    fontSize: 15,
    color: pdfColors.webDevInk,
    marginBottom: 10,
    lineHeight: 1.3,
  },
  webDevSummary: {
    fontSize: 8,
    color: pdfColors.webDevInk,
    lineHeight: 1.35,
    textAlign: "justify",
    marginBottom: 8,
  },
  webDevAvatar: {
    width: 72,
    height: 72,
    objectFit: "cover",
    alignSelf: "center",
    marginBottom: 8,
  },
  webDevAvatarPlaceholder: {
    width: 72,
    height: 72,
    backgroundColor: pdfColors.webDevBandTop,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 12,
  },
  webDevAvatarInitials: {
    fontSize: 24,
    fontWeight: 700,
    color: pdfColors.webDevInk,
    opacity: 0.5,
  },
  webDevSectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
    marginBottom: 3,
  },
  webDevSectionIconBadge: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: pdfColors.webDevInk,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 6,
  },
  webDevSectionIconLetter: {
    fontSize: 7,
    fontWeight: 700,
    color: pdfColors.webDevPageInner,
  },
  webDevSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.webDevInk,
    letterSpacing: 1.65,
    textTransform: "uppercase",
  },
  webDevHr: {
    height: 1,
    width: "100%",
    backgroundColor: pdfColors.webDevInk,
    marginBottom: 5,
  },
  webDevContactRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    paddingBottom: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: pdfColors.webDevInk,
  },
  webDevContactIconBadge: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: pdfColors.webDevInk,
    alignItems: "center",
    justifyContent: "center",
  },
  webDevContactIconLetter: {
    fontSize: 8,
    fontWeight: 700,
    color: pdfColors.webDevPageInner,
  },
  webDevContactDivider: {
    width: 1,
    height: 12,
    backgroundColor: pdfColors.webDevInk,
    marginHorizontal: 6,
  },
  webDevContactText: {
    fontSize: 9,
    color: pdfColors.webDevInk,
    opacity: 0.8,
    flex: 1,
  },
  webDevSkillCol: {
    width: "48%",
  },
  webDevSkillRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  webDevSkillItem: {
    fontSize: 8,
    color: pdfColors.webDevInk,
    marginBottom: 4,
  },
  webDevAwardTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: pdfColors.webDevInk,
    marginBottom: 2,
  },
  webDevAwardMeta: {
    fontSize: 9,
    color: pdfColors.webDevInk,
    opacity: 0.7,
    marginBottom: 8,
  },
  webDevTimelineBlock: {
    marginBottom: 6,
  },
  webDevTimelineEntryTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.webDevInk,
    marginBottom: 2,
  },
  webDevTimelineEntrySub: {
    fontSize: 8,
    color: pdfColors.webDevInk,
    opacity: 0.7,
    marginBottom: 4,
  },
  webDevTimelineBullet: {
    fontSize: 9,
    color: pdfColors.webDevInk,
    lineHeight: 1.4,
    marginBottom: 3,
    flex: 1,
  },
  webDevTimelineDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: pdfColors.webDevInk,
    marginRight: 6,
    marginTop: 3,
  },
  webDevTimelineBulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 2,
  },
  webDevCertDate: {
    fontSize: 8,
    color: pdfColors.webDevInk,
    opacity: 0.7,
  },
  webDevFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: pdfColors.webDevInk,
  },
  webDevFooterSlot: {
    alignItems: "center",
    maxWidth: "22%",
  },
  webDevFooterIconBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: pdfColors.webDevInk,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  webDevFooterIconLetter: {
    fontSize: 8,
    fontWeight: 700,
    color: pdfColors.webDevPageInner,
  },
  webDevFooterText: {
    fontSize: 8,
    color: pdfColors.webDevInk,
    textAlign: "center",
  },
});
